#!/bin/sh
echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"
echo "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body>"
echo "<h3>Originators</h3>"
echo "<pre>"
batctl o | cat
echo "</pre>"
echo "</body></html>"
