#!/bin/sh
echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"

echo "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body>"
echo "<h1>Router Status</h1>"
echo "<h2>Main Info</h2>"
echo "<pre>"
echo "NodeID: "$(cat /etc/nodeid) | cat
echo "</pre>"
echo "<pre>"
echo "Hostname: "$(uci -q get system.@system[0].hostname) | cat
echo "</pre>"
echo "<pre>"
echo "Version: "$(cat /etc/banner | grep config) | cat
echo "</pre>"
echo "<h2>Batman-ADV</h2>"
echo "<h3>Batman Version</h3>"
echo "<pre>"
batctl -v | cat
echo "</pre>"
echo "<h3>Originators</h3>"
echo "<pre>"
batctl o | cat
echo "</pre>"
echo "<h3>Global Translation Table</h3>"
echo "<pre>"
batctl tg | cat
echo "</pre>"
echo "<h3>Local Translation Table</h3>"
echo "<pre>"
batctl tl | cat
echo "</pre>"
echo "<h3>Gateway Mode</h3>"
echo "<pre>"
batctl gw | cat
echo "</pre>"
echo "<h3>Gateways</h3>"
echo "<pre>"
batctl gwl | cat
echo "</pre>"
echo "<h3>Bridge Loop Avoidance Claim Table</h3>"
echo "<pre>"
batctl cl | cat
echo "</pre>"
echo "<h3>Mesh Statistics</h3>"
echo "<pre>"
batctl s | cat
echo "</pre>"
echo "<h2>Network & Wifi</h2>"
echo "<h3>Network Interfaces</h3>"
echo "<pre>"
ifconfig | cat
echo "</pre>"
echo "<h3>Network Bridge Status</h3>"
echo "<pre>"
brctl show | cat
echo "</pre>"
echo "<h3>Wifi Adhoc Stations</h3>"
echo "<pre>"
iw dev wlan0-1 station dump | cat
echo "</pre>"
echo "<h3>Wifi AP Stations</h3>"
echo "<pre>"
iw dev wlan0 station dump | cat 
echo "</pre>"
echo "<h2>P2ptbl Info</h2>"
echo "<h3>GWIP Table</h3>"
echo "<pre>"
p2ptbl show /tmp/p2ptbl/gwip | cat
echo "</pre>"
echo "<h2>System Info</h2>"
echo "<h3>Processes</h3>"
echo "<pre>"
ps w | cat
echo "</pre>"
echo "<h3>UCI</h3>"
echo "<pre>"
uci show | cat
echo "</pre>"
echo "<h3>Syslog</h3>"
echo "<pre>"
logread | cat
echo "</pre>"
echo "<h3>Kernel log</h3>"
echo "<pre>"
dmesg | cat
echo "</pre>"
echo "</body></html>"